spring:
  profiles.include:
    - db
    - oauth2
    - jwt
  web:
    cors:
#       allowed-origins: https://velog-clone-657tefkqj-park21700305s-projects.vercel.app
         allowed-origins: http://localhost:3000