spring:
  datasource:
    url: jdbc:mysql://localhost:3306/velog?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: park
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop  # 자동으로 DB 스키마를 업데이트하는 설정 (옵션)
  defer-datasource-initialization: true

